---
- name: Chainlayer ETH Node Playbook
  hosts: all
  user: ubuntu
  tasks:
    - name: Update apt
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
    
    - name: install chrony for smoother time sync
      become: yes
      apt:
        name: chrony
        state: latest

    - name: start and enable chrony service
      become: yes
      systemd:
        name: chrony
        state: started
        enabled: yes

    # - import_tasks: tasks/docker.yml