---
- name: Chainlayer ETH Node Playbook
  hosts: all
  become: yes
  vars:
    docker_compose_version: "v2.2.2"
  user: ubuntu
  tasks:
    - name: Update apt
      become: yes
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: yes
    
    - name: install chrony for smoother time sync
      become: yes
      apt:
        name: chrony
        state: latest

    - name: start and enable chrony service
      become: yes
      systemd:
        name: chrony
        state: started
        enabled: yes

    - import_tasks: tasks/docker.yml