---
- name: Grafana - Install deps
  apt: 
      name: apt-transport-https
      state: present
      update_cache: yes

- name: Grafana - Add gpg key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: Grafana - Add repo 
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Grafana - Install
  apt: 
      name: grafana
      state: present
      update_cache: yes

- name: Grafana - Enable and start grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started

# Has some issues using the prom datasource.
# For now, just manually import the dashboard: 1860
#
# - name: Grafana - Import node exporter dashboard
#   grafana_dashboard:
#     grafana_url: http://localhost:3000
#     dashboard_id: 1860
#   tags: dash
